name: distkv_build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout@v2 action
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install the dependencies
        run: ./scripts/install_dependencies.sh
      - name: package Distkv
        run: ./build.sh
      - name: distkv test case result
        run: mvn test
      - name: report the result of code coverage
        run: bash <(curl -s https://codecov.io/bash)

  install_python_package:
    runs-on: ubuntu-latest
    steps:
    - name: use checkout@v2 action
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install the dependencies
      run: bash ./scripts/install_dependencies.sh
    - name: install python package
      run: cd deploy/python && pip install -e . -v
