name: distkv build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout@v2 action
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up drpc env
        run: ./scripts/install_dependencies.sh
      - name: distkv package
        run: mvn clean install -DskipTests
      - name: distkv test case result
        run: mvn test